apiVersion: couchbase.com/v1
kind: CouchbaseCluster
metadata:
  name: cb1-viride-acme
spec:
  baseImage: couchbase/server
  version: enterprise-6.0.1
  paused: false
  antiAffinity: true
  authSecret: cb-viride-acme-auth
  exposeAdminConsole: true
  adminConsoleServices:
    - data
  exposedFeatures:
    - xdcr
  logRetentionTime: 604800s
  logRetentionCount: 20
  cluster:
    dataServiceMemoryQuota: 256
    indexServiceMemoryQuota: 256
    searchServiceMemoryQuota: 256
    eventingServiceMemoryQuota: 256
    analyticsServiceMemoryQuota: 1024
    indexStorageSetting: memory_optimized
    autoFailoverTimeout: 120
    autoFailoverMaxCount: 3
    autoFailoverOnDataDiskIssues: true
    autoFailoverOnDataDiskIssuesTimePeriod: 120
    autoFailoverServerGroup: false
  buckets:
    - name: cb1-viride-acme-bucket
      type: couchbase
      memoryQuota: 128
      replicas: 1
      ioPriority: high
      evictionPolicy: fullEviction
      conflictResolution: seqno
      enableFlush: true
      enableIndexReplica: false
  serverGroups:
    - us-east1-c
    - us-east1-b
  servers:
    - size: 2
      name: all_services
      services:
        - data
        - index
        - query
        - search
        - eventing
        - analytics
      serverGroups:
        - us-east1-c
        - us-east1-b
    - size: 2
      name: data_services
      services:
        - data
      serverGroups:
        - us-east1-c
        - us-east1-b
  
  