apiVersion: v1
kind: PersistentVolume
metadata:
  name: us-east1-c-cluster1
spec:
  capacity:
    storage: 10Gi
  # volumeMode field requires BlockVolume Alpha feature gate to be enabled.
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  local:
    path: /mnt/stateful_partition/home/vishalaggarwal27/cl1pv
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - gke-viride-cluster-3-default-pool-883a4cb3-4pns
          - gke-viride-cluster-3-default-pool-883a4cb3-b82z