apiVersion: couchbase.com/v1
kind: CouchbaseCluster
metadata:
  name: cb-viride-acme
spec:
  baseImage: couchbase/server
  version: enterprise-6.0.1
  paused: false
  antiAffinity: true
  authSecret: cb-viride-acme-auth
  exposeAdminConsole: true
  adminConsoleServices:
    - data
  exposedFeatures:
    - xdcr
    - client
  exposedFeatureServiceType: NodePort
  logRetentionTime: 604800s
  logRetentionCount: 20
  cluster:
    dataServiceMemoryQuota: 256
    indexServiceMemoryQuota: 256
    searchServiceMemoryQuota: 256
    eventingServiceMemoryQuota: 256
    analyticsServiceMemoryQuota: 1024
    indexStorageSetting: memory_optimized
    autoFailoverTimeout: 10
    autoFailoverMaxCount: 3
    autoFailoverOnDataDiskIssues: true
    autoFailoverOnDataDiskIssuesTimePeriod: 120
    autoFailoverServerGroup: false
  buckets:
    - name: cb-viride-acme-bucket
      type: couchbase
      memoryQuota: 128
      replicas: 1
      ioPriority: high
      evictionPolicy: fullEviction
      conflictResolution: seqno
      enableFlush: true
      enableIndexReplica: false
  servers:
    - size: 1
      name: all_services
      services:
        - data
        - index
        - query
        - search
        - eventing
        - analytics
      pod:
        volumeMounts:
          default: viride-pv1
  volumeClaimTemplates:
    - metadata:
        name: viride-pv1
      spec:
        storageClassName: standard
        resources:
          requests:
            storage: 1Gi