apiVersion: v1
kind: PersistentVolume
metadata:
  name: viride-pv
spec:
  capacity:
    storage: 10Gi
  # volumeMode field requires BlockVolume Alpha feature gate to be enabled.
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  local:
    path: /mnt/stateful_partition/home/vishalaggarwal27/pv
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - gke-viride-cluster-2-default-pool-8ac6011a-2s45
          - gke-viride-cluster-2-default-pool-8ac6011a-t6lt
          - gke-viride-cluster-2-default-pool-8ac6011a-w054 